services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8890:8080"
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_LOG_LEVEL: INFO
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: xforwarded
      KC_SPI_THEME_DEFAULT: my-theme
    depends_on:
      keycloakdb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - keycloak-network

  keycloakdb:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - keycloak-network

volumes:
  keycloak_data:

networks:
  keycloak-network:
